create table orders
(
    id   int8 generated by default as identity,
    client_name varchar(255) not null,
    client_email varchar(255) not null,
    delivery_address varchar(255) not null,
    order_date  timestamp default current_timestamp,
    total_sum double8 not null,
    user_id int8,
    primary key (id)
);
create table orders_products
(
    order_id    int8 not null,
    products_id int8 not null
);
create table products
(
    id int8 not null,
    name_product varchar(255) not null,
    description varchar(500) not null,
    price double4 not null,
    amount int4 not null,
    image varchar(255) not null
);
create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);
create table users
(
    id int8 not null,
    name varchar(255) not null,
    lastname varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    address varchar(255) not null,
    primary key (id)
);
create table users_products_list
(
    user_id         int8 not null,
    products_list_id int8 not null
);
create table review
(
    id int8 not null,
    date timestamp default current_timestamp,
    client_name varchar(255) not null,
    client_email varchar(255) not null,
    rating double4 not null,
    text_review varchar(500),
    products_id int8, not null,
    primary key (id)
);
alter table if exists orders
    add constraint foreign key (user_id) references users;
alter table if exists orders_products
    add constraint foreign key (products_id) references products;
alter table if exists orders_products
    add constraint foreign key (order_id) references orders;
alter table if exists user_role
    add constraint foreign key (user_id) references users;
alter table if exists users_products_list
    add constraint foreign key (products_list_id) references products;
alter table if exists users_products_list
    add constraint foreign key (user_id) references users;