spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sportshop
    password: myshop
    username: alexa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


